name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm test
        env:
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
      - name: Publish image
        uses: elgohr/Publish-Docker-Github-Action@3.03
        with:
          name: hakanensari/country
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
